### ISSUE TITLE
[Better chests] The mod is completely down.

### ISSUE THREAD

**Issue by Gage55** [ImJustMatt/ExpandedStorage#114]
(Since I am not a native English speaker, the following text has been translated from my native English using an online translator)

The mod is not fully operational until SMAPI issues the boot error shown on the screen. It started today, I'm guessing because of the November 5 SMAPI update.

![изображение_2024-11-05_193904877](https://github.com/user-attachments/assets/6653bccc-e6b3-42fe-a776-2e55eecf18be)

**Comment by Gage55** [comment]
- Better Chests 2.18.3 because initialization failed:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_IsLocalPlayerInventory' in type 'StardewMods.BetterChests.Framework.Models.HeldItemsWrapper' from assembly 'BetterChests, Version=2.18.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at StardewModdingAPI.Framework.SCore.TryLoadModEntry(IModMetadata metadata, Assembly modAssembly, Mod& mod, String& error) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/SCore.cs:line 2137
   at StardewModdingAPI.Framework.SCore.TryLoadMod(IModMetadata mod, IModMetadata[] mods, List`1 modAssemblyLoadContexts, AssemblyLoader assemblyLoader, IInterfaceProxyFactory proxyFactory, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase, HashSet`1 suppressUpdateChecks, Nullable`1& failReason, String& errorReasonPhrase, String& errorDetails) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/SCore.cs:line 2028
TypeLoadException: Method 'get_IsLocalPlayerInventory' in type 'StardewMods.BetterChests.Framework.Models.HeldItemsWrapper' from assembly 'BetterChests, Version=2.18.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

P.S. If you need a line of error in text format.
