### ISSUE TITLE
Disabling Search Tabs causes continuous SMAPI error spam when chests are open in 1.5.5 beta

### ISSUE THREAD

**Issue by InsanityPrelude** [ImJustMatt/ExpandedStorage#17]
```
NullReferenceException: Object reference not set to an instance of an object.
   at XSPlus.Features.CommonFeature.OnRenderingActiveMenu(Object sender, RenderingActiveMenuEventArgs e) in C:\Users\Matthew\RiderProjects\StardewMods\XSPlus\Features\CommonFeature.cs:line 182
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args, Func`2 match) in SMAPI\Framework\Events\ManagedEvent.cs:line 126
```
If it's not specific to this one mod, I'd say the most likely culprit seems to be ChestsAnywhere, which has a few other small incompatibilities.  Notably, the reason I turned off the chest filter tabs is that they frequently render underneath my inventory when using ChestsAnywhere.

Here's a full SMAPI log in the smapi.io analyzer: https://smapi.io/log/51fc136399944d7ebd48dea0ff4c5129

**Comment by InsanityPrelude** [comment]
Actually, the problem appears to be resolved completely when updating my mods to XSLite_1.7.1-beta.7 and XSPlus_1.0.0-beta-5 from the Discord server, so perhaps it's already been addressed.
